"""Assemble the static, browser-only annotator for GitHub Pages.

There is no bundler and no npm here on purpose. The app is three script files
and a stylesheet with no imports and no dependencies, so a build step would add
a toolchain to maintain and buy nothing. Assembling the site is a copy, a
generated index and a one-line config change.

What the static build differs in, and only this:

  * `config.js` is rewritten to mode "local", so `store.js` uses localStorage
    instead of POSTing to a server that is not there.
  * `manifest.json` replaces the `/api/models` route, which cannot exist
    without a server. It is the list of plans the site ships with.
  * The plans are copied in as static assets under `data/`.

    python annotator/build_site.py --out dist
    python -m http.server -d dist 8080      # to check it before pushing
"""

from __future__ import annotations

import argparse
import glob
import json
import os
import shutil
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
STATIC = os.path.join(HERE, "static")
DATA = os.path.join(HERE, "data")

# Everything the page loads. Listed explicitly rather than copying the folder,
# so a stray file cannot be published by accident.
ASSETS = ["index.html", "style.css", "app.js", "compose.js", "store.js",
          "fsdir.js", "viewer3d.js"]


def build(out: str, quiet: bool = False) -> int:
    plans = sorted(glob.glob(os.path.join(DATA, "*.plan.json")))
    if not plans:
        print("!! no plans in annotator/data — nothing to publish")
        print("   run: python main/export_plans.py 'dataset/test_set/*.ifc' "
              "--out annotator/data")
        return 1

    if os.path.exists(out):
        shutil.rmtree(out)
    os.makedirs(os.path.join(out, "data"), exist_ok=True)

    for a in ASSETS:
        src = os.path.join(STATIC, a)
        if not os.path.exists(src):
            print(f"!! missing asset {a}")
            return 1
        shutil.copy2(src, os.path.join(out, a))

    # The one behavioural difference between the two builds.
    with open(os.path.join(out, "config.js"), "w") as fh:
        fh.write(
            "/* Generated by annotator/build_site.py -- do not edit.\n"
            " * The static build has no server, so annotations live in this\n"
            " * browser's localStorage and are handed back as a file.\n"
            " */\n"
            'window.BIMSG_CONFIG = { mode: "local" };\n')

    models = []
    for p in plans:
        name = os.path.basename(p).replace(".plan.json", "")
        with open(p) as fh:
            doc = json.load(fh)
        shutil.copy2(p, os.path.join(out, "data", os.path.basename(p)))
        n_rooms = sum(len(s["rooms"]) for s in doc["storeys"])
        n_edges = sum(len(s["edges"]) for s in doc["storeys"])
        n_vert = len(doc.get("vertical") or [])
        models.append({
            "model": name, "storeys": len(doc["storeys"]),
            "rooms": n_rooms, "edges": n_edges, "vertical": n_vert,
            "items": n_rooms + n_edges + n_vert,
        })

    with open(os.path.join(out, "manifest.json"), "w") as fh:
        json.dump({"format": "bimsg-plan-manifest", "version": 1,
                   "models": models}, fh, indent=1)

    # Pages deployed from an Actions artifact is not run through Jekyll, so this
    # is only insurance -- but it costs nothing and a `_`-prefixed file
    # appearing later would otherwise vanish silently.
    open(os.path.join(out, ".nojekyll"), "w").close()

    # A copy of the guide, so annotators are never told to go and find a file
    # in a repository they may not have.
    guide = os.path.join(HERE, "ANNOTATION_GUIDE.md")
    if os.path.exists(guide):
        shutil.copy2(guide, os.path.join(out, "ANNOTATION_GUIDE.md"))

    size = sum(os.path.getsize(os.path.join(dp, f))
               for dp, _, fs in os.walk(out) for f in fs)
    if not quiet:
        print(f"static site -> {out}")
        print(f"  {len(models)} plans, "
              f"{sum(m['rooms'] for m in models)} rooms, "
              f"{sum(m['items'] for m in models)} judgeable items")
        print(f"  {size / 1e6:.2f} MB total")
        print(f"\n  preview:  python -m http.server -d {out} 8080")
    return 0


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--out", default="dist")
    ap.add_argument("--quiet", action="store_true")
    args = ap.parse_args()
    return build(args.out, args.quiet)


if __name__ == "__main__":
    sys.exit(main())
