"""Assemble the static, browser-only annotator for GitHub Pages.

There is no bundler and no npm here on purpose. The app is three script files
and a stylesheet with no imports and no dependencies, so a build step would add
a toolchain to maintain and buy nothing. Assembling the site is a copy, a
generated index and a one-line config change.

What the static build differs in, and only this:

  * `config.js` is rewritten to mode "local", so `store.js` uses localStorage
    instead of POSTing to a server that is not there.
  * `manifest.json` replaces the `/api/models` route, which cannot exist
    without a server. It is the list of plans the site ships with.
  * The plans are copied in as static assets under `data/`, along with any
    IFC file sitting beside them -- that is what lets someone using the hosted
    site open the 3D view, which otherwise needs a folder on their own disk.

    python annotator/build_site.py --out dist
    python -m http.server -d dist 8080      # to check it before pushing
"""

from __future__ import annotations

import argparse
import glob
import json
import os
import shutil
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
STATIC = os.path.join(HERE, "static")
DATA = os.path.join(HERE, "data")

# Everything the page loads. Listed explicitly rather than copying the folder,
# so a stray file cannot be published by accident.
ASSETS = ["index.html", "style.css", "app.js", "compose.js", "store.js",
          "fsdir.js", "viewer3d.js"]


def build(out: str, quiet: bool = False, with_ifc: bool = True,
          plans_dir: str | None = None) -> int:
    # `resolve_pins.py` writes an augmented plan set to its own directory;
    # without this the only way to publish it was to copy over annotator/data.
    src = plans_dir or DATA
    plans = sorted(glob.glob(os.path.join(src, "*.plan.json")))
    if not plans:
        print("!! no plans in annotator/data — nothing to publish")
        print(f"   looked in {src}")
        print("   run: python main/export_plans.py 'dataset/test_set/*.ifc' "
              "--out annotator/data")
        return 1

    if os.path.exists(out):
        shutil.rmtree(out)
    os.makedirs(os.path.join(out, "data"), exist_ok=True)

    for a in ASSETS:
        src = os.path.join(STATIC, a)
        if not os.path.exists(src):
            print(f"!! missing asset {a}")
            return 1
        shutil.copy2(src, os.path.join(out, a))

    # The one behavioural difference between the two builds.
    with open(os.path.join(out, "config.js"), "w") as fh:
        fh.write(
            "/* Generated by annotator/build_site.py -- do not edit.\n"
            " * The static build has no server, so annotations live in this\n"
            " * browser's localStorage and are handed back as a file.\n"
            " */\n"
            'window.BIMSG_CONFIG = { mode: "local" };\n')

    models, ifc_bytes = [], 0
    for p in plans:
        name = os.path.basename(p).replace(".plan.json", "")
        with open(p) as fh:
            doc = json.load(fh)
        shutil.copy2(p, os.path.join(out, "data", os.path.basename(p)))
        n_rooms = sum(len(s["rooms"]) for s in doc["storeys"])
        n_edges = sum(len(s["edges"]) for s in doc["storeys"])
        n_vert = len(doc.get("vertical") or [])

        # The IFC is optional and large. Publishing it is what makes the 3D
        # check available to someone working from the hosted site rather than
        # from a folder on their own disk; its size goes into the manifest so
        # the page can warn before pulling 29 MB over a phone connection.
        src_ifc = os.path.join(src, f"{name}.ifc")
        size = 0
        if with_ifc and os.path.exists(src_ifc):
            shutil.copy2(src_ifc, os.path.join(out, "data", f"{name}.ifc"))
            size = os.path.getsize(src_ifc)
            ifc_bytes += size

        models.append({
            "model": name, "storeys": len(doc["storeys"]),
            "rooms": n_rooms, "edges": n_edges, "vertical": n_vert,
            "items": n_rooms + n_edges + n_vert,
            "hasIfc": size > 0, "ifcBytes": size,
        })

    with open(os.path.join(out, "manifest.json"), "w") as fh:
        json.dump({"format": "bimsg-plan-manifest", "version": 1,
                   "models": models}, fh, indent=1)

    # Pages deployed from an Actions artifact is not run through Jekyll, so this
    # is only insurance -- but it costs nothing and a `_`-prefixed file
    # appearing later would otherwise vanish silently.
    open(os.path.join(out, ".nojekyll"), "w").close()

    # A copy of the guide, so annotators are never told to go and find a file
    # in a repository they may not have.
    guide = os.path.join(HERE, "ANNOTATION_GUIDE.md")
    if os.path.exists(guide):
        shutil.copy2(guide, os.path.join(out, "ANNOTATION_GUIDE.md"))

    size = sum(os.path.getsize(os.path.join(dp, f))
               for dp, _, fs in os.walk(out) for f in fs)
    if not quiet:
        print(f"static site -> {out}")
        print(f"  {len(models)} plans, "
              f"{sum(m['rooms'] for m in models)} rooms, "
              f"{sum(m['items'] for m in models)} judgeable items")
        n_ifc = sum(1 for m in models if m["hasIfc"])
        print(f"  {n_ifc} IFC file(s) published ({ifc_bytes / 1e6:.0f} MB)"
              if n_ifc else "  no IFC files (the 3D view will be unavailable)")
        print(f"  {size / 1e6:.2f} MB total")
        if size > 900e6:
            print("  !! over 900 MB — GitHub Pages refuses to publish a site "
                  "larger than 1 GB")
        print(f"\n  preview:  python -m http.server -d {out} 8080")
    return 0


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--out", default="dist")
    ap.add_argument("--quiet", action="store_true")
    ap.add_argument("--no-ifc", action="store_true",
                    help="leave the IFC files out; the 3D view needs them")
    ap.add_argument("--plans", help="plan directory to publish "
                                    "(default annotator/data)")
    args = ap.parse_args()
    return build(args.out, args.quiet, with_ifc=not args.no_ifc,
                 plans_dir=args.plans)


if __name__ == "__main__":
    sys.exit(main())
